name: first0ne
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  json_annotation:
    path: D:/First App/first0ne/Package/json_annotation  # مسیر محلی پکیج

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # فقط در بخش dev_dependencies باشد
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/Venum.jpg
    - assets/Oppenheimer.jpg
    - assets/Interstellar.jpg
    - assets/TheDarkKnight.jpg
    - assets/Deadpool3.jpg
    - assets/TheCrow.jpeg
    - assets/JohnWick.jpg
